# Generated by Django 5.0.6 on 2024-07-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_payment_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="borrowing",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
    ]
