# Generated by Django 5.0.6 on 2024-07-12 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0002_initial"),
        ("payment", "0004_remove_payment_borrowing_remove_payment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="borrowing",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrowing",
                to="borrowing.borrowing",
            ),
            preserve_default=False,
        ),
    ]
